# Remote theme directory
remote_theme: analytics-link/analytics-link.github.io

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme

#-------------------------------
# General Site Settings
title: Alec Damley-Jones
description: "Hi, I'm Alec, and I'm a Data Scientist.  My portfolio focuses on interesting projects I've recently undertaken, with a clear focus on business impact. Please see the links below for my CV, Github and LinkedIn pages. Thanks for reading!"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# About Section
subtitle: Data Science <span style="color:#f58506"> Portfolio </span>
location: "London, UK"
resume_url: /docs/Alec_DamleyJones_CV_04-2026.pdf
avatar_image: /img/IMG_5213-removebg-preview.png

#-------------------------------
# Contact links
linkedln: "https://www.linkedin.com/in/alec-damley-jones-2467b41a7/" # Add your linkedln handle
github: "https://github.com/alec-dj"  # Add your github handle

paginate: 6
paginate_path: "/page/:num"

sass:
  sass_dir: _sass
  style: compressed # possible values: nested expanded compact compressed

defaults:
  - scope:
      type: posts
    values:
      layout: post
      read_time: true
      share: false


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/



